//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BsqView.rc
//
#define IDC_SPECT_VIEWER                3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_BSQVIETYPE                  129
#define IDD_DIALOG1                     130
#define IDD_IMAGEINITIATE               130
#define IDD_DIALOG2                     131
#define IDD_SELBANDSDLG                 131
#define IDR_MENU1                       132
#define IDD_FLAT_DIALOG                 132
#define IDD_KMEANS_PARAMETERS           133
#define IDR_ZPROFILE                    133
#define IDD_ISODATA                     134
#define IDR_ZPROFILE1                   134
#define IDD_INPUTOUT                    136
#define IDD_LINE_DIALOG                 137
#define IDD_INPUT_FILE_DLG              137
#define IDD_SUPERFILECONTROL            138
#define IDD_SUPERVISEDSECOND            139
#define IDD_SAM_PARAMETRE               140
#define IDD_SPECTRL_LIBRARY             141
#define IDD_SPECTRAL_LIBRARY            141
#define IDD_SPECTRAL_PROFILE            142
#define IDR_INPUT_SPECTRAL              142
#define IDD_LINE_DLG_PARA               143
#define IDD_LINE_OUTPUT_DLG             143
#define IDD_CHOOSE_AREAS                144
#define IDD_FLAT_DLG_BG                 145
#define IDD_FLAT_DLG                    145
#define IDD_LINE_DLG_BG                 146
#define IDD_LINE_DLG                    146
#define IDD_INPUT_SPECTRAL_DLG          147
#define IDD_SAVE_ASCII                  148
#define IDD_DIALOG3                     149
#define IDD_BIG_IMAGE_DLG               149
#define IDD_DIALOG4                     150
#define IDD_SMALL_IMAGE_DLG             150
#define IDD_SAVE_SPELIB                 151
#define IDC_CURSOR1                     151
#define IDD_SPECTRAL_PROFILE2           152
#define IDD_COMBINE_CLASSES             153
#define IDD_COMBINE_PARAMETRE           154
#define IDD_COLOR_PICKER                155
#define IDD_COMBINE_CLASSES_OUTPUT      156
#define IDR_CHOOSE_FILE                 157
#define IDD_MINI_DISTANCE               157
#define IDD_CLASSES_FILE                158
#define IDD_CLASSES_STATISTICS          159
#define IDD_CLASSES_SELECTION           160
#define IDR_MENU2                       160
#define IDD_CLASSES_STATISTICS_OUTPUT   161
#define IDD_SPECTRAL_RESAMPLE           162
#define IDD_CLASSES_SUMMARY             163
#define IDR_SENSOR                      163
#define IDD_DIALOGTRACE                 164
#define IDD_CLASSES_SINGLE              165
#define IDD_SPECTRAL_BULIDER            165
#define IDR_CLASSES_STATSTICS           166
#define IDD_AREA_STAT                   166
#define IDD_CLASS_INFORMATION           167
#define IDD_PALLETTE                    168
#define IDD_PROGRESS_DLG                169
#define IDD_SELECTED_AREAS              170
#define IDD_RESAMPLE_SAVE_FILE          171
#define IDD_SPE_BULD_EDIT_NAME          172
#define IDD_SPE_BULD_EDIT_PLOT          173
#define IDR_SPECTRAL_LIBRARY_BUILDER    174
#define IDD_BANDS_MATH_PAIR             174
#define IDD_DIALOG5                     174
#define IDD_BANDS_MATH                  175
#define IDD_PLOT_PARAMETER              176
#define IDD_COLORT_RGBTOHSIINPUT        177
#define IDD_COLORT_RGBTOHSIPARA         178
#define IDR_NDVI_SENSOR                 178
#define IDD_COLORT_HSITORGBINPUT        179
#define IDD_COLORT_HSITORGBPARA         180
#define IDD_COLORT_RGBTOCMYKINPUT       181
#define IDD_COLORT_RGBTOCMYKPARA        182
#define IDD_COLORT_CMYKTORGBINPUT       183
#define IDD_COLORT_CMYKTORGBPARA        184
#define IDD_NDVI_DLG                    185
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_DRAW_Z_PROFILE              1001
#define IDC_EDIT3                       1002
#define IDC_PLOT_NUM                    1002
#define IDC_EDIT4                       1003
#define IDC_EDIT_CLASSSTDEV             1003
#define IDC_OBJECTNAME                  1003
#define IDC_SEL_NUM                     1003
#define IDC_EDITBLUE                    1003
#define IDC_EDIT5                       1004
#define IDC_EDIT_MINCLASSSTANCE         1004
#define IDC_SEL_ALL                     1004
#define IDC_EDIT6                       1005
#define IDC_EDIT_MAXPAIRS               1005
#define IDC_CLEAR_ALL                   1005
#define IDC_DRAW_PLOT                   1006
#define IDC_Y_PRECISION                 1006
#define IDC_PLOT_DELETE                 1007
#define IDC_X_PRECISION                 1007
#define IDC_FLAT_INPUT_FILE             1008
#define IDC_PLOT_MODIFY                 1008
#define IDC_FLOAT_REPORT                1008
#define IDC_FLAT_OUTPUT_FILE            1009
#define IDC_PLOT_ADD                    1009
#define IDC_CHOOSE_SAVE                 1009
#define IDC_PLOT_CLEAR                  1010
#define IDC_SAVEFILEPATH                1010
#define ID_LINE_LIST                    1011
#define ID_FLAT_LIST                    1011
#define IDC_GREY                        1012
#define IDC_LINE_REFLECTION             1012
#define IDC_RGB                         1013
#define IDC_LINE_INPUT_FILE             1013
#define IDC_LIST1                       1014
#define IDC_LINE_OUTPUT_FILE            1014
#define IDC_OPEN_LIBRARY                1014
#define IDC_R                           1015
#define IDC_OUTPUT_FILE                 1015
#define IDC_G                           1016
#define IDC_B                           1017
#define IDC_STATIC_R                    1019
#define IDC_STATIC_G                    1020
#define IDC_STATIC_B                    1021
#define IDC_LIBRARYNAME1                1021
#define IDC_STATIC_PROPERIETY           1022
#define IDC_EDIT_CLASSNUMBER            1023
#define IDC_BIG_IMAGE                   1023
#define IDC_EDIT_ITERATIONTIMES         1024
#define IDC_SMALL_IMAGE                 1024
#define IDC_changethreshold             1025
#define IDC_EDIT_MINPIXEL               1026
#define IDC_EDIT_ITENUMBER              1027
#define IDC_BUTTON1                     1030
#define IDC_BUTTON3                     1031
#define IDC_BUTTON4                     1032
#define IDC_BUTTON2                     1033
#define IDC_OUTFILE                     1034
#define IDC_OUTFILEPATH                 1036
#define IDC_ISODATA_OUTFILE             1039
#define IDC_SUPERVISED_INPUT_FILE       1040
#define IDC_FLAT_PA_MEMORY              1040
#define IDC_LINE_BG_INPUT_FILE          1040
#define IDC_SUPERVISED_OUTPUT_FILE      1041
#define IDC_FLAT_PA_FILE                1041
#define IDC_LINE_BG_LIST_FILE           1041
#define IDC_SUPERVISEDSAM_INPUT_FILE    1042
#define IDC_FLAT_PA_CHOOSE              1042
#define IDC_LINE_BG_STATIC_FILE         1042
#define IDC_FLAT_PA_EDIT                1043
#define IDC_INPUT_SPECTRAL_DEL          1043
#define IDC_INPUT_SPELTRAL_LIST         1044
#define IDC_PLOT_LIST                   1044
#define IDC_AREA_LIST                   1044
#define IDC_FLAT_PA_LIST                1045
#define IDC_SAVE_NUM                    1045
#define IDC_COMBINE_INFORMATION         1045
#define IDC_DRAW_Z_PROFILE2             1045
#define IDC_LINE_PA_CHOOSE              1046
#define IDC_INPUT_FILE                  1046
#define IDC_PROGRESS1                   1046
#define IDC_PLOT_TITLE                  1046
#define IDC_LINE_PA_EDIT                1047
#define IDC_SAVE_SL_PATH                1047
#define IDC_ADD_COMBINATION             1047
#define IDC_DISPLAY_DATA                1047
#define IDC_PROGRESS_STATIC             1047
#define IDC_BACKGRD                     1047
#define IDC_SAVEPATHSL                  1048
#define IDC_INPUT_FILENAME              1048
#define IDC_PLOTGRD                     1048
#define IDC_LINE_BG_INPUT_FIELD         1049
#define IDC_OUTPUT_FILENAME             1049
#define IDC_SCROLLCLASSNUM              1049
#define IDC_SCREDITGREEN                1049
#define IDC_LINE_BG_LIST_FIELD          1050
#define IDC_CHOOSE_EDIT                 1050
#define IDC_SELECT_FILE                 1050
#define IDC_EDIT_CLASSNUM               1050
#define IDC_LINE_BG_STATIC_FIELD        1051
#define IDC_CHOOSE_ERASE                1051
#define IDC_INPUT_DATA_FILE             1051
#define IDC_CHOOSE_DEL                  1052
#define IDC_PATHNAME                    1052
#define IDC_INPUT_ASCII_FILE            1052
#define IDC_CHOOSE_NEW                  1053
#define IDC_FILELIST                    1053
#define IDC_USER_DEFI_FUNC              1053
#define IDC_PRE_DEFI_FUNC               1054
#define IDC_LINE_BG_PEIDUI              1055
#define IDC_SENSOR_TYPE                 1055
#define IDC_LINE_BG_LIST_PEIDUI         1056
#define IDC_CLASSES_LIST                1056
#define IDC_CLASSES_NUMBER              1057
#define IDC_CHOOSE_FIND                 1058
#define IDC_SELECT_ALL                  1058
#define IDC_CHOOSE_MEAN                 1059
#define IDC_SELECT_REPORT_FILE          1059
#define IDC_DELETE_ALL                  1059
#define IDC_CHOOSE_GROW                 1060
#define IDC_SAVE_FILE                   1060
#define IDC_CHOOSE_STATE                1061
#define IDC_RADIO2                      1061
#define IDC_RE_PLOT_NUM                 1061
#define IDC_CLASS_COLOR                 1062
#define IDC_RE_SEL_NUM                  1062
#define IDC_X_AXIS                      1062
#define IDC_RE_CHOOSE_SAVE              1063
#define IDC_Y_AXIS                      1063
#define IDC_RE_SAVEFILEPATH             1064
#define IDC_AXIS_TITLE                  1064
#define IDC_AXIS_MINIMUM                1065
#define IDC_AXIS_MAXIMUM                1066
#define IDC_TICK_STYLE_IN               1067
#define IDC_REDSCROLLBAR                1068
#define IDC_BYTE                        1068
#define IDC_TICK_STYLE_OUT              1068
#define IDC_GreenSCROLLBAR              1069
#define IDC_FLOAT                       1069
#define IDC_TICK_STYLE_GRID             1069
#define IDC_BLUESCROLLBAR               1070
#define IDC_INT                         1070
#define IDC_TICK_STYLE_OFF              1070
#define IDC_EDITRED                     1071
#define IDC_STANDARD_IMAGE              1071
#define IDC_TICK_MARKS_AUTO             1071
#define IDC_EDITGREEN                   1072
#define IDC_CLASSIFICATION_IMAGE        1072
#define IDC_TICK_MARKS_FIXED            1072
#define IDC_SCREDITRED                  1073
#define IDC_MD_CLASSES_LIST             1073
#define IDC_SCREDITBLUE                 1074
#define IDC_LINE_OK                     1074
#define IDC_MD_CLASSES_NUMBER           1074
#define IDC_PROGRESS_IN                 1075
#define IDC_MD_PATHNAME                 1075
#define IDC_BUTTON_COLOR_LIST           1076
#define IDC_PROGRESS_OUT                1076
#define IDC_TRACE_IMAGE                 1077
#define IDC_SELECTED_NUMBER             1077
#define IDC_CLASSES_SUMMARY             1078
#define IDC_SOURCE                      1078
#define IDC_MATHS_DEL                   1078
#define IDC_CLASSES_SINGLE              1079
#define IDC_OUTPUT_BANDS_SUM            1079
#define IDC_LIST_PRE                    1079
#define IDC_CANCEL                      1079
#define IDC_SELECTED_SPECTRA_SUM        1080
#define IDC_LIST_RGBTOHSI               1080
#define IDC_SELECTED_SPECTRA_LIST       1081
#define IDC_EXP                         1081
#define IDC_RGBTOHSI_INPUTINFO          1081
#define IDC_DELETE_SPECTRUM             1082
#define IDC_RTOH_CHOOSE                 1082
#define IDC_RESET_NAME                  1083
#define ID_OKOK                         1083
#define IDC_RTOH_EDIT                   1083
#define IDC_CURRENT_NAME_LIST           1084
#define IDC_INPUTFILE_EDIT              1084
#define IDC_HSITORGB_LIST               1084
#define IDC_EDIT_SELECT_ITEM            1085
#define IDC_CHOOSE                      1085
#define IDC_H_RADIO                     1085
#define IDC_SPE_BULD_PLOT               1086
#define IDC_PRE_STATIC                  1086
#define IDC_I_RADIO                     1086
#define IDCANCLE                        1087
#define IDC_LIST_BANDS                  1087
#define IDC_S_RADIO                     1087
#define IDC_HEADER_SENSOR               1088
#define IDC_LIST_VARI                   1088
#define IDC_FILE_INFORMATION            1089
#define IDC_NDVI_CHOOSE                 1089
#define IDC_STATISTIC_INFORMATION       1090
#define IDC_EDVI_OUTFILE                1090
#define IDC_STATIC_PRO                  1091
#define IDC_EDVI_FILE_TYPE              1091
#define IDC_H_STATIC                    1092
#define IDC_NDVI_RED                    1092
#define IDC_S_STATIC                    1093
#define IDC_NDVI_NEARRED                1093
#define IDC_I_STATIC                    1094
#define IDC_HSITORGB_INPUTINFO          1095
#define IDC_HTOR_CHOOSE                 1096
#define IDC_HTOR_EDIT                   1097
#define IDC_LIST_RGBTOCMYK              1098
#define IDC_RGBTOCMYK_INPUTINFO         1099
#define IDC_RTOC_CHOOSE                 1100
#define IDC_RTOC_EDIT                   1101
#define IDC_CMYKTORGB_LIST              1102
#define IDC_C_STATIC                    1103
#define IDC_M_STATIC                    1104
#define IDC_Y_STATIC                    1105
#define IDC_C_RADIO                     1106
#define IDC_M_RADIO                     1107
#define IDC_Y_RADIO                     1108
#define IDC_STATIC_PROR                 1109
#define IDC_CMYKTORGB_INPUTINFO         1110
#define IDC_CTOR_CHOOSE                 1111
#define IDC_CTOR_EDIT                   1112
#define ID_SELBANDSDLG_OPEN             32771
#define ID_SELBANDSDLG_FILELIST         32772
#define ID_SAVE_AS_ASCII                32772
#define ID_SELBANDSDIALOG_CLOSE         32773
#define ID_SAVE_AS_SPELIB               32773
#define ID_SELBANDSDLG_CLOSEALL         32774
#define ID_COLLECT_PLOT                 32774
#define ID_SELBANDSDLG_CANCEL           32775
#define ID_REMOVE_PLOT                  32775
#define ID_CHOOSEAREA                   32776
#define ID_KMEANS                       32778
#define ID_ISODATA                      32779
#define ID_FLAT_DINGBIAO                32780
#define ID_LINE_DINGBIAO                32781
#define ID_MINIMUM_DISTANCE             32782
#define ID_INPUT_TEXT                   32782
#define ID_SPECTRAL_ANGLE_MAPPER        32783
#define ID_INPUT_SPECTRAL               32783
#define ID_SPECTRAL_LIBRARY             32784
#define ID_Z_PROFILE                    32785
#define ID_AREASTAT                     32786
#define ID_COMBINE_CLASSES              32787
#define ID_STATISTICS_CLASSES           32788
#define ID_COLOR_BLACK                  32788
#define ID_CLASSES_TEXT                 32789
#define ID_COLOR_RED                    32789
#define ID_CANCEL_SAVE                  32790
#define ID_GREEN                        32790
#define ID_VIEW_TEST                    32790
#define ID_BLUE                         32791
#define ID_FROM_ASCLL                   32791
#define ID_COLOR_SANDYBEIGE             32792
#define ID_FROM_SPE                     32792
#define ID_COLOR_CYAN                   32793
#define ID_FROM_INTRTIN                 32793
#define ID_COLOR_YELLOW                 32794
#define ID_TRACE                        32794
#define ID_SENSOR_LANDSAT_TM5           32794
#define ID_COLOR_PURPLE                 32795
#define ID_SENSOR_LANDSAT_TM7           32795
#define ID_SPECTRAL_RESAMPLE            32795
#define ID_COLOR_CORAL                  32796
#define ID_SENSOR_MSS4                  32796
#define ID_COLORT_HTOR                  32796
#define ID_COLOR_ORANGE                 32797
#define ID_SENSOR_SPOT1                 32797
#define ID_COLORT_RTOC                  32797
#define ID_COLOR_GOLD                   32798
#define ID_SENSOR_SPOT4                 32798
#define ID_COLORT_CTOR                  32798
#define ID_COLOR_NACARAT                32799
#define ID_SENSOR_LANDSAT_TM4           32799
#define ID_COLOR_OLIVEGREEN             32800
#define ID_SENSOR_MODIS                 32800
#define ID_COLORT_HTOC                  32800
#define ID_COLOR_ROSINESS               32801
#define ID_SENSOR_MSS5                  32801
#define ID_COLORT_CTOH                  32801
#define ID_COLOR_ETIOLATION             32802
#define ID_COLOR_GRAY                   32803
#define ID_SENSOR_LANDSAT_MSS5          32803
#define IDC_BUILDER_SAVE_ASCII          32803
#define ID_COLOR_SAFFRON                32804
#define ID_SENSOR_LANDSAT_MSS4          32804
#define IDC_BUILDER_SAVE_SPE_LIBRARY    32804
#define ID_COLOR_SKYBLUE                32805
#define IDC_BUILDER_IMPORT_ASCII        32805
#define ID_SPECTRAL_LIBRARY_BUILDER     32805
#define IDC_BUILDER_OPTIONS_NAME        32806
#define ID_BAND_MATH                    32806
#define ID_PLOT_PARAMETER               32806
#define ID_COLOR_NIGHTBLUE              32807
#define IDC_BUILDER_OPTION_PLOT         32807
#define ID_COLORT_RTOH                  32807
#define ID_COLOR_AUBERGINE              32808
#define IDC_BUILDER_HELP                32808
#define ID_SENSOR_TM                    32808
#define ID_NDVI_CACU                    32808
#define ID_COLOR_PEACOCK                32809
#define ID_SENSOR_MSS                   32809
#define ID_NDVI_CAC                     32809
#define ID_COLOR_ALMOND                 32810
#define ID_SENSOR_AVHRR                 32810
#define ID_COLOR_SPRINGGREEN            32811
#define ID_SENSOR_SPOT                  32811
#define ID_COLOR_TOMATO                 32812
#define ID_COLOR_FLAX                   32813
#define ID_COLOR_FUCHSINE               32814
#define ID_COLOR_SEABLUE                32815
#define ID_COLOR_LILAC                  32816
#define ID_COLOR_LITTLEGOLD             32817
#define ID_COLOR_PAWPAW                 32818
#define ID_COLOR_WHEATYELLOW            32819
#define ID_WHITE                        32820
#define ID_COLOR_YELLOW2                32821
#define ID_BLUE2                        32822
#define ID_YELLOW3                      32823
#define ID_GREEN2                       32824
#define ID_COLOR_HONEYDEW               32825
#define ID_RED2                         32826
#define ID_RED3                         32827
#define ID_COLOR_LILAC2                 32828
#define ID_LEFT                         61446
#define ID_RIGHT                        61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1091
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
